# app/api/v1/endpoints/forms.py
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from sqlalchemy.orm import selectinload
from typing import List, Optional
from pydantic import BaseModel, Field

from app.core.database import get_async_session
from app.api.dependencies.auth import get_current_user, get_researcher_or_admin_user
from app.models.form import Form, FormCreate, FormRead, FormUpdate
from app.models.question import Question, QuestionCreate, QuestionRead, QuestionType
from app.models.study import Study # Needed to check if study exists
from app.models.user import User # Needed for type hinting in dependencies

router = APIRouter()

# --- Pydantic Schemas for LLM Integration ---
class LLMQuestionSchema(BaseModel):
    """Schema for a question generated by the LLM service."""
    question_text: str = Field(..., description="The text of the question.")
    question_type: str = Field(..., description="The type of the question (e.g., 'text', 'radio').")
    options: Optional[List[str]] = Field(None, description="A list of options for multiple-choice questions.")
    is_required: bool = Field(False, description="Indicates if the question is mandatory.")

class LLMFormSchema(BaseModel):
    """Schema for a form generated by the LLM service."""
    study_id: int = Field(..., description="The ID of the study this form belongs to.")
    title: str = Field(..., description="The title of the form.")
    description: str = Field(..., description="The description of the form.")
    questions: List[LLMQuestionSchema] = Field(..., description="A list of questions for the form.")

# --- CRUD Endpoints for Forms ---

@router.post("/", response_model=FormRead, status_code=status.HTTP_201_CREATED, summary="Create a new form for a study")
async def create_form(
    form_create: FormCreate,
    session: AsyncSession = Depends(get_async_session),
    current_user: User = Depends(get_researcher_or_admin_user)
):
    """
    Create a new form associated with a study.
    - Only users with 'researcher' or 'administrator' roles can create forms.
    """
    # Check if the study exists
    study_query = await session.execute(select(Study).where(Study.id == form_create.study_id))
    study = study_query.scalars().first()
    if not study:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Study not found")

    # If the user is a researcher, they must be the owner of the study
    if current_user.role.name == "researcher" and study.creator_id != current_user.id:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not authorized to create forms for this study")

    db_form = Form(**form_create.model_dump(), creator_id=current_user.id)
    session.add(db_form)
    await session.commit()
    await session.refresh(db_form)
    return db_form

@router.get("/", response_model=List[FormRead], summary="Retrieve all forms")
async def get_all_forms(
    session: AsyncSession = Depends(get_async_session),
    current_user: User = Depends(get_researcher_or_admin_user)
):
    """
    Retrieve a list of all forms.
    - If the user is an administrator, they get all forms.
    - If the user is a researcher, they only get forms for studies they own.
    """
    if current_user.role.name == "administrator":
        result = await session.execute(select(Form).options(selectinload(Form.questions)))
    else: # researcher
        result = await session.execute(
            select(Form)
            .join(Study)
            .where(Study.creator_id == current_user.id)
            .options(selectinload(Form.questions))
        )
    return result.scalars().all()

@router.get("/by_study/{study_id}", response_model=List[FormRead], summary="Get all forms for a specific study")
async def get_forms_by_study(
    study_id: int,
    session: AsyncSession = Depends(get_async_session),
    current_user: User = Depends(get_current_user)
):
    """
    Retrieve all forms associated with a given study ID.
    """
    # Check if the study exists first
    study_exists = await session.scalar(select(Study.id).where(Study.id == study_id))
    if not study_exists:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Study not found.")

    # Eagerly load the `questions` relationship to prevent MissingGreenlet errors.
    # This ensures that when the FormRead model is validated, the `form.questions`
    # attribute is already populated within the active session context.
    result = await session.execute(
        select(Form)
        .where(Form.study_id == study_id)
        .options(selectinload(Form.questions))
    )
    forms = result.scalars().all()

    # The validation will now succeed because `form.questions` is pre-loaded.
    return [FormRead.model_validate(form, from_attributes=True) for form in forms]



@router.get("/{form_id}", response_model=FormRead, summary="Retrieve a single form by ID")
async def get_form(
    form_id: int,
    session: AsyncSession = Depends(get_async_session),
    current_user: User = Depends(get_researcher_or_admin_user)
):
    """
    Retrieve a single form by its ID, with its questions eagerly loaded.
    - The user must be a researcher who owns the study or an administrator.
    """
    result = await session.execute(
        select(Form)
        .where(Form.id == form_id)
        .options(selectinload(Form.questions).selectinload(Question.options))
        .options(selectinload(Form.study)) # Eager load study for permission check
    )
    db_form = result.scalars().first()

    if not db_form:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Form not found")
    
    # Check permissions
    if current_user.role.name == "researcher" and db_form.study.creator_id != current_user.id:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not authorized to view this form")

    return db_form

@router.put("/{form_id}", response_model=FormRead, summary="Update a form")
async def update_form(
    form_id: int,
    form_update: FormUpdate,
    session: AsyncSession = Depends(get_async_session),
    current_user: User = Depends(get_researcher_or_admin_user)
):
    """
    Update a form by its ID.
    - The user must be a researcher who owns the study or an administrator.
    """
    result = await session.execute(
        select(Form)
        .where(Form.id == form_id)
        .options(selectinload(Form.study)) # Eager load study for permission check
    )
    db_form = result.scalars().first()

    if not db_form:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Form not found")

    # Check permissions
    if current_user.role.name == "researcher" and db_form.study.creator_id != current_user.id:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not authorized to update this form")

    update_data = form_update.model_dump(exclude_unset=True)
    for key, value in update_data.items():
        setattr(db_form, key, value)

    session.add(db_form)
    await session.commit()
    await session.refresh(db_form)
    
    # Eagerly load the questions for the response
    result_refreshed = await session.execute(
        select(Form)
        .where(Form.id == form_id)
        .options(selectinload(Form.questions))
    )
    db_form_refreshed = result_refreshed.scalars().first()
    
    return db_form_refreshed

@router.delete("/{form_id}", status_code=status.HTTP_204_NO_CONTENT, summary="Delete a form by ID")
async def delete_form(
    form_id: int,
    session: AsyncSession = Depends(get_async_session),
    current_user: User = Depends(get_researcher_or_admin_user)
):
    """
    Delete a form by its ID.
    - Only users with 'researcher' or 'administrator' roles can delete forms.
    """
    result = await session.execute(
        select(Form)
        .where(Form.id == form_id)
        .options(selectinload(Form.study)) # Load study to check permissions
    )
    db_form = result.scalars().first()

    if not db_form:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Form not found")
    
    # Check permissions
    if current_user.role.name == "researcher" and db_form.study.creator_id != current_user.id:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not authorized to delete this form")

    await session.delete(db_form)
    await session.commit()
    return

# --- LLM Integration Endpoint ---
@router.post("/from-llm", response_model=FormRead, status_code=status.HTTP_201_CREATED, summary="Create a new form and questions from an LLM payload")
async def create_form_from_llm(
    llm_form_data: LLMFormSchema,
    session: AsyncSession = Depends(get_async_session),
    current_user: User = Depends(get_researcher_or_admin_user)
):
    """
    Create a new form and its questions using data from an LLM service.
    - The user must be a researcher who owns the study or an administrator.
    """
    # 1. Verify that the study exists
    study_query = await session.execute(select(Study).where(Study.id == llm_form_data.study_id))
    study = study_query.scalars().first()
    if not study:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Study not found")
    
    # 2. Check permissions
    if current_user.role.name == "researcher" and study.creator_id != current_user.id:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not authorized to create forms for this study")

    # 3. Create the new Form
    new_form_data = FormCreate(
        study_id=llm_form_data.study_id,
        title=llm_form_data.title,
        description=llm_form_data.description
    )
    db_form = Form(**new_form_data.model_dump(), creator_id=current_user.id)
    session.add(db_form)
    await session.commit()
    await session.refresh(db_form)

    # 4. Create the questions and associate them with the new form
    for llm_question in llm_form_data.questions:
        # Determine the QuestionType enum from the string
        question_type = QuestionType[llm_question.question_type.upper()]
        
        # Create a new question
        new_question_data = QuestionCreate(
            form_id=db_form.id,
            question_text=llm_question.question_text,
            question_type=question_type,
            options=llm_question.options,
            is_required=llm_question.is_required
        )
        db_question = Question(**new_question_data.model_dump())
        session.add(db_question)

    await session.commit()
    await session.refresh(db_form, attribute_names=["questions"])
    
    # Eagerly load the questions for the final response
    result_refreshed = await session.execute(
        select(Form)
        .where(Form.id == db_form.id)
        .options(selectinload(Form.questions).selectinload(Question.options))
    )
    db_form_refreshed = result_refreshed.scalars().first()

    return db_form_refreshed