# app/api/v1/endpoints/forms.py
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from sqlalchemy.orm import selectinload
from typing import List, Optional
from pydantic import BaseModel, Field

from app.core.database import get_async_session
from app.api.dependencies.auth import get_current_user, get_researcher_or_admin_user, get_llm_admin_user
from app.models.form import Form, FormCreate, FormRead, FormUpdate
from app.models.question import Question, QuestionCreate
from app.models.study import Study # Needed to check if study exists
from app.models.user import User # Needed for type hinting in dependencies
from app.api.dependencies import auth # Import auth module for get_password_hash if needed for other endpoints or user creation.

router = APIRouter()

# --- New Pydantic Schemas for LLM Integration ---
class LLMQuestionSchema(BaseModel):
    """Schema for a question generated by the LLM service."""
    question_text: str = Field(..., description="The text of the question.")
    question_type: str = Field(..., description="The type of the question (e.g., 'text', 'radio').")
    options: Optional[List[str]] = Field(None, description="A list of options for multiple-choice questions.")
    is_required: bool = Field(False, description="Indicates if the question is mandatory.")

class LLMFormSchema(BaseModel):
    """Schema for a form generated by the LLM service."""
    study_id: int = Field(..., description="The ID of the study this form belongs to.")
    title: str = Field(..., description="The title of the form.")
    description: str = Field(..., description="The description of the form.")
    questions: List[LLMQuestionSchema] = Field(..., description="A list of questions for the form.")

@router.post("/", response_model=FormRead, status_code=status.HTTP_201_CREATED, summary="Create a new form for a study")
async def create_form(
    form_create: FormCreate,
    session: AsyncSession = Depends(get_async_session),
    current_user: User = Depends(get_researcher_or_admin_user)
):
    """
    Create a new form associated with a study.
    - Only users with 'researcher' or 'administrator' roles can create forms.
    """
    # Check if the study exists
    study_query = await session.execute(select(Study).where(Study.id == form_create.study_id))
    study = study_query.scalars().first()
    if not study:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Study not found.")

    new_form = Form(
        study_id=form_create.study_id,
        user_id=current_user.id, # Assign the current user as the creator
        title=form_create.title,
        description=form_create.description
    )
    session.add(new_form)
    await session.commit()
    await session.refresh(new_form)
    # Eagerly load the questions for the response
    new_form.questions # This will trigger the lazy load now that the session is active.
    return new_form

@router.post("/from-llm", response_model=FormRead, status_code=status.HTTP_201_CREATED, summary="Create a new form and questions from an LLM-generated JSON schema")
async def create_form_from_llm(
    form_data: LLMFormSchema,
    session: AsyncSession = Depends(get_async_session),
    current_user: User = Depends(get_llm_admin_user) # Secure the endpoint for LLM service only
):
    """
    Creates a new form and its associated questions from a JSON schema generated by an LLM service.
    
    This endpoint is designed to be called by the LLM service itself.
    It requires authentication via the `get_llm_admin_user` dependency.
    """
    # 1. Verify that the study exists
    study_query = await session.execute(select(Study).where(Study.id == form_data.study_id))
    study = study_query.scalars().first()
    if not study:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Study with ID {form_data.study_id} not found.")

    # 2. Create the new Form object
    new_form = Form(
        study_id=form_data.study_id,
        user_id=current_user.id, # Assign the LLM service's user as the creator
        title=form_data.title,
        description=form_data.description
    )
    session.add(new_form)
    await session.flush() # Flush to get the new form's ID

    # 3. Create the Question objects and associate them with the new form
    for question_data in form_data.questions:
        question_create_data = QuestionCreate(
            form_id=new_form.id,
            question_text=question_data.question_text,
            question_type=question_data.question_type,
            options=question_data.options,
            is_required=question_data.is_required
        )
        new_question = Question(**question_create_data.model_dump())
        session.add(new_question)

    await session.commit()
    await session.refresh(new_form)

    # 4. Eagerly load the questions for the final response
    result_refreshed = await session.execute(
        select(Form)
        .where(Form.id == new_form.id)
        .options(selectinload(Form.questions))
    )
    db_form_refreshed = result_refreshed.scalars().first()
    
    return db_form_refreshed

@router.get("/by_study/{study_id}", response_model=List[FormRead], summary="Get all forms for a specific study")
async def get_forms_by_study(
    study_id: int,
    session: AsyncSession = Depends(get_async_session),
    current_user: User = Depends(get_current_user)
):
    """
    Retrieve all forms associated with a given study ID.
    """
    # Check if the study exists first
    study_exists = await session.scalar(select(Study.id).where(Study.id == study_id))
    if not study_exists:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Study not found.")

    # Eagerly load the `questions` relationship to prevent MissingGreenlet errors.
    # This ensures that when the FormRead model is validated, the `form.questions`
    # attribute is already populated within the active session context.
    result = await session.execute(
        select(Form)
        .where(Form.study_id == study_id)
        .options(selectinload(Form.questions))
    )
    forms = result.scalars().all()

    # The validation will now succeed because `form.questions` is pre-loaded.
    return [FormRead.model_validate(form, from_attributes=True) for form in forms]


@router.get("/{form_id}", response_model=FormRead, summary="Get a single form by ID")
async def get_form(
    form_id: int,
    session: AsyncSession = Depends(get_async_session),
    current_user: User = Depends(get_current_user)
):
    """
    Retrieve a single form by its ID.
    """
    # Also eagerly load questions here to avoid the same error
    result = await session.execute(
        select(Form)
        .where(Form.id == form_id)
        .options(selectinload(Form.questions))
    )
    db_form = result.scalars().first()
    if not db_form:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Form not found")
    return db_form

@router.put("/{form_id}", response_model=FormRead, summary="Update an existing form")
async def update_form(
    form_id: int,
    form_update: FormUpdate,
    session: AsyncSession = Depends(get_async_session),
    current_user: User = Depends(get_researcher_or_admin_user)
):
    """
    Update an existing form by its ID.
    - Only users with 'researcher' or 'administrator' roles can update forms.
    """
    result = await session.execute(
        select(Form)
        .where(Form.id == form_id)
        .options(selectinload(Form.created_by_user)) # Load creator to check permissions
    )
    db_form = result.scalars().first()

    if not db_form:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Form not found")

    # Check for authorization. Creator must be current user or user must be admin.
    if current_user.role.name == "researcher" and db_form.created_by_user.id != current_user.id:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not authorized to update this form.")

    update_data = form_update.model_dump(exclude_unset=True)
    for key, value in update_data.items():
        setattr(db_form, key, value)

    session.add(db_form)
    await session.commit()
    await session.refresh(db_form)
    
    # Eagerly load the questions for the response
    result_refreshed = await session.execute(
        select(Form)
        .where(Form.id == form_id)
        .options(selectinload(Form.questions))
    )
    db_form_refreshed = result_refreshed.scalars().first()
    
    return db_form_refreshed

@router.delete("/{form_id}", status_code=status.HTTP_204_NO_CONTENT, summary="Delete a form by ID")
async def delete_form(
    form_id: int,
    session: AsyncSession = Depends(get_async_session),
    current_user: User = Depends(get_researcher_or_admin_user)
):
    """
    Delete a form by its ID.
    - Only users with 'researcher' or 'administrator' roles can delete forms.
    """
    result = await session.execute(
        select(Form)
        .where(Form.id == form_id)
        .options(selectinload(Form.created_by_user)) # Load creator to check permissions
    )
    db_form = result.scalars().first()

    if not db_form:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Form not found")

    # Check authorization based on the user's role
    if current_user.role.name == "researcher" and db_form.created_by_user.id != current_user.id:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not authorized to delete this form.")

    await session.delete(db_form)
    await session.commit()
    return None