from datetime import datetime
from enum import Enum
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

# models for Criteria Augmentation
class CriteriaAugmentationRequest(BaseModel):
    researcher_input: str = Field(..., description="The researcher's natural language input for criteria.")

class SuggestedRule(BaseModel):
    description: str = Field(..., description="A clear description of the suggested rule.")
    structured_format: Optional[str] = Field(None, description="An optional structured format for the rule (e.g., JSON, YAML, pseudocode).")

class CriteriaAugmentationResponse(BaseModel):
    clearer_wording: str = Field(..., description="The LLM's suggested clearer phrasing for the criteria.")
    suggested_rules: List[Dict[str, str]] = Field(..., description="Suggested structured rule templates.")
    version_id: int = Field(..., description="Unique ID for this version of the augmented criteria.")
    version_number: int = Field(..., description="Sequential version number for this specific input.")
    original_input_hash: str = Field(..., description="Hash of the original input, for grouping versions.")
    llm_model_used: str = Field(..., description="The LLM model used for this generation.")
    version_timestamp: datetime = Field(..., description="Timestamp of when this version was generated.")
    modified_by: str = Field(..., description="Indicates if the content was generated by 'LLM' or 'Human'.") # NEW
    refinement_of_version_id: Optional[int] = Field(None, description="The ID of the version this content refined, if applicable.")
    
class CriteriaVersionDetails(BaseModel):
    version_id: int = Field(..., description="Unique ID for this version.")
    version_number: int = Field(..., description="Sequential version number.")
    original_input: str = Field(..., description="The original researcher input for this version.")
    llm_output: Dict[str, Any] = Field(..., description="The LLM-generated or human-modified output (parsed JSON).")
    llm_model_used: str = Field(..., description="The LLM model used for this generation (or 'Human Refined').")
    version_timestamp: datetime = Field(..., description="Timestamp of generation.")
    modified_by: str = Field(..., description="Indicates if the content was generated by 'LLM' or 'Human'.")
    refinement_of_version_id: Optional[int] = Field(None, description="The ID of the version this content refined, if applicable.") # NEW

class FormVersionDetails(BaseModel):
    version_id: int = Field(..., description="Unique ID for this version.")
    version_number: int = Field(..., description="Sequential version number.")
    original_input: str = Field(..., description="The original study objectives for this version.")
    llm_output_json_schema: Dict[str, Any] = Field(..., description="The LLM-generated or human-modified JSON schema (parsed JSON).")
    llm_model_used: str = Field(..., description="The LLM model used for this generation (or 'Human Refined').")
    version_timestamp: datetime = Field(..., description="Timestamp of generation.")
    modified_by: str = Field(..., description="Indicates if the content was generated by 'LLM' or 'Human'.")
    refinement_of_version_id: Optional[int] = Field(None, description="The ID of the version this content refined, if applicable.")

#models for Smart Form Generation
class FormGenerateRequest(BaseModel):
    study_objectives: str = Field(..., description="A description of the study's objectives, used to generate the form schema.")
    additional_context: Optional[str] = Field(None, description="Optional additional context or requirements for the form (e.g., specific field types, validation rules).")

class FormGenerationResponse(BaseModel):
    json_schema: Dict[str, Any] = Field(..., description="The generated JSON schema definition for the form.")
    version_id: int = Field(..., description="Unique ID for this version of the generated form.")
    version_number: int = Field(..., description="Sequential version number for this specific input.")
    original_input_hash: str = Field(..., description="Hash of the original input, for grouping versions.")
    llm_model_used: str = Field(..., description="The LLM model used for this generation.")
    version_timestamp: datetime = Field(..., description="Timestamp of when this version was generated.")
    modified_by: str = Field(..., description="Indicates if the content was generated by 'LLM' or 'Human'.") 
    refinement_of_version_id: Optional[int] = Field(None, description="The ID of the version this content refined, if applicable.")
    
class CriteriaRefinementRequest(BaseModel):
    refined_output: Dict[str, Any] = Field(..., description="The complete, human-modified JSON output for the criteria.")

class FormRefinementRequest(BaseModel):
    refined_output: Dict[str, Any] = Field(..., description="The complete, human-modified JSON schema output for the form.")
    
class SummaryContext(str, Enum):
    """Defines different contexts for summarization."""
    general = "general"
    specialist_clinical = "specialist_clinical"
    high_level_findings = "high_level_findings"
    # Add more contexts as needed

class TextSummarizeRequest(BaseModel):
    text_content: str = Field(..., description="The long block of text (e.g., clinical note, report) to be summarized.")
    summary_context: SummaryContext = Field(
        SummaryContext.general,
        description="The context for summarization, influencing the prompt engineered for the LLM."
    )
    target_length: Optional[str] = Field(
        None,
        description="Optional: Desired summary length (e.g., 'brief', 'detailed', 'one paragraph')."
    )

class TextSummarizeResponse(BaseModel):
    summary: str = Field(..., description="The concise summary generated by the LLM.")
    llm_raw_output: Optional[str] = Field(None, description="The raw output from the LLM for debugging/inspection.")
    
# models for Contextual Q&A (RAG) and chat history items
class ChatHistoryItem(BaseModel):
    role: str = Field(..., description="Role of the message sender (e.g., 'user', 'assistant').")
    content: str = Field(..., description="Content of the chat message.")

# Update QnARequest to include chat history
class QnARequest(BaseModel):
    question: str = Field(..., description="The user's question to be answered by the RAG system.")
    num_context_chunks: int = Field(5, description="Number of relevant document chunks to retrieve from the knowledge base.", ge=1, le=10)
    chat_history: Optional[List[ChatHistoryItem]] = Field(None, description="Previous turns of the conversation for conversational context.")

class QnAResponse(BaseModel):
    answer: str = Field(..., description="The answer to the question, based on the knowledge base.")
    sources: List[str] = Field(..., description="List of document sources (e.g., file paths) used to generate the answer.")
    retrieved_chunks: Optional[List[str]] = Field(None, description="The raw text content of the chunks retrieved from the vector store.")
    llm_raw_output: Optional[str] = Field(None, description="The raw output from the LLM for debugging/inspection.")
    history_summarized: Optional[bool] = Field(False, description="Indicates if the chat history was summarized before processing.")  